# Generated by Django 3.0.3 on 2021-03-22 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuel', '0002_auto_20200905_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.Car')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'custom_consumption',
                'verbose_name_plural': 'custom_consumptions',
            },
        ),
    ]
