# Generated by Django 3.0.3 on 2021-03-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_customconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(default='GT3', max_length=5),
        ),
        migrations.AddField(
            model_name='track',
            name='lap_time_gt4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='lap_time',
            field=models.FloatField(default=0),
        ),
    ]
